Repository team-yaza/mozi-server, pull requests merged in 2022-09, with the labels that each got.

#92 feat: 장소 검색시 가장 가까운 위치부터 결과를 확인할 수 있는 기능
  src/controllers/location.ts
  src/routes/index.ts
  src/routes/location.ts
  src/services/location.ts
Labels: feature

#91 feat: kakao login
  src/controllers/auth.ts
  src/loaders/express.ts
  src/loaders/index.ts
  src/loaders/passport.ts
  src/loaders/sequelize.ts
  src/models/index.ts
  src/models/user.ts
  src/routes/auth.ts
Labels: feature

#93 feat: kakao login with no libraries
  package.json
  src/config/index.ts
  src/controllers/auth.ts
  src/index.ts
  src/loaders/express.ts
  src/middlewares/login.ts
  src/models/user.ts
  src/routes/auth.ts
  src/services/kakao.ts
  src/utils/kakaoStrategy.ts
  src/utils/localStrategy.ts
  yarn.lock
Labels: feature

#94 feat: get todos with location (service, router, controller)
  src/controllers/location.ts
  src/routes/location.ts
  src/services/location.ts
Labels: feature

#95 feat: Todo 테이블에 soft_deleted 필드 추가
  src/models/todo.ts
Labels: feature

#96 feat: Todo Model에 pk 추가
  src/controllers/auth.ts
  src/models/todo.ts
Labels: feature, refactor

#97 feat: jwt token verify middleware
  src/middlewares/auth.ts
  src/types/index.d.ts
  src/types/user.ts
  tsconfig.json
  yarn.lock
Labels: feature

#98 feat: Todo 생성시 uuid로 id 만들기
  package.json
  src/services/todo.ts
  yarn.lock
Labels: feature

#100 feat: User와 Todo Model 관계 정의
  .eslintrc.json
  src/controllers/auth.ts
  src/controllers/webpush.ts
  src/loaders/sequelize.ts
  src/middlewares/auth.ts
  src/models/index.ts
  src/models/todo.ts
  src/models/user.ts
  src/services/location.ts
  src/services/todo.ts
Labels: feature

#99 feat: getAllTodos, createTodo에 protect middleware 적용해서 로그인 테스트
  package.json
  src/controllers/auth.ts
  src/controllers/todo.ts
  src/middlewares/auth.ts
  src/routes/index.ts
  src/services/todo.ts
  src/types/index.d.ts
  tsconfig.json
Labels: feature, refactor

#101 feat: ownerId를 통한 Todo 전부 삭제 api
  src/controllers/todo.ts
  src/middlewares/auth.ts
  src/routes/todo.ts
  src/services/todo.ts
  src/types/user.ts
Labels: feature

#102 feat: Todo model index 컬럼 추가
  src/models/todo.ts
Labels: feature

#103 chore: cors 설정 추가
  src/loaders/express.ts
Labels: chore

#104 fix: jwt malformed 오류 해결
  src/middlewares/auth.ts
Labels: bug

#105 fix: cookie 저장 방법 수정
  src/controllers/auth.ts
Labels: feature

#106 refactor: todo update 방법 변경
  src/controllers/todo.ts
  src/services/todo.ts
Labels: refactor

#107 feat: todo index field added
  src/models/index.ts
  src/models/todo.ts
Labels: feature

#108 docs: Create LICENSE
  LICENSE
Labels: dependencies

#109 refactor: todo update service
  src/services/todo.ts
Labels: refactor

#110 feat: Express.Request.user defined
  package.json
  src/controllers/todo.ts
  src/types/express.d.ts
  src/types/user.ts
Labels: feature

#112 fix: req.user assertion
  src/controllers/todo.ts
Labels: refactor

#115 feat: cross-env added
  package.json
  src/loaders/sequelize.ts
  yarn.lock
Labels: feature

#117 feat: todo soft delete
  src/loaders/sequelize.ts
  src/models/index.ts
  src/services/todo.ts
Labels: feature

#118 fix: docker 내부 static ip로 설정
  docker-compose.yml
  nginx/nginx.conf
Labels: bug

#119 feat: api document updated
  swagger.yaml
Labels: documentation

#120 feat: db 쿼리에 paranoid option 추가
  src/middlewares/auth.ts
  src/routes/todo.ts
  src/services/todo.ts
Labels: feature

#121 feat: todo schema locationName added
  src/middlewares/auth.ts
  src/models/index.ts
  src/models/todo.ts
  src/services/todo.ts
Labels: feature

#122 chore: merge 되는 경우만 CD & docker 내부 시간 한국으로 맞추기
  .github/workflows/cd.yml
  docker-compose.yml
Labels: chore

#123 feat: api docs updated
  swagger.yaml
Labels: documentation

#124 feat: todo, user interface added
  src/types/todo.ts
  src/types/user.ts
Labels: feature
