Repository team-yaza/mozi-server, pull requests merged in 2022-07, with the labels that each got.

#2 chore: TypeScript, Node, Express 세팅
  .prettierrc
  package.json
  src/config/index.ts
  src/controllers/index.ts
  src/index.ts
  src/loaders/express.ts
  src/loaders/index.ts
  src/loaders/mongo.ts
  src/middlewares/index.ts
  src/routes/index.ts
  src/services/index.ts
  src/utils/index.ts
  tsconfig.json
  yarn.lock
Labels: chore

#9 chore: jest setting
  .prettierrc
  jest.config.js
  package.json
  src/index.ts
  tests/index.ts
  tests/setup.ts
  tsconfig.json
  yarn.lock
Labels: chore

#13 feat: 데이터 베이스 설계 및 기본 Controller, Service
  package.json
  src/controllers/area.ts
  src/controllers/header.ts
  src/controllers/project.ts
  src/controllers/todo.ts
  src/loaders/express.ts
  src/loaders/index.ts
  src/models/area.ts
  src/models/header.ts
  src/models/project.ts
  src/models/todo.ts
  src/routes/area.ts
  src/routes/header.ts
  src/routes/index.ts
  src/routes/project.ts
  src/routes/todo.ts
  src/services/area.ts
  src/services/header.ts
  src/services/project.ts
  src/services/todo.ts
  yarn.lock
Labels: feature

#20 fix: husky setting
  .husky/pre-commit
  package.json
Labels: bug

#22 feat:데이터베이스에서 요청된 할 일 삭제
  src/controllers/todo.ts
  src/routes/todo.ts
  src/services/todo.ts
Labels: feature

#25 fix: delete todo api
  src/services/todo.ts
Labels: bug

#27 feat: continuous integration
  .eslintrc.json
  .github/workflows/ci.yml
  jest.config.js
  package.json
  src/controllers/area.ts
  tsconfig.json
Labels: feature

#29 feat: asyncHandler 적용 및 에러처리
  src/controllers/area.ts
  src/controllers/header.ts
  src/controllers/project.ts
  src/controllers/todo.ts
  src/loaders/express.ts
  src/routes/area.ts
  src/routes/header.ts
  src/routes/project.ts
  src/utils/asyncHandler.ts
Labels: feature

#30 feat: Restful한 api 설정
  src/controllers/todo.ts
  src/routes/index.ts
  src/routes/todo.ts
  src/services/todo.ts
Labels: feature, refactor

#32 chore: start script 추가
  .gitignore
  package.json
  tsconfig.json
Labels: chore

#34 chore: appspec 수정
  appspec.yml
  scripts/start.sh
Labels: chore

#37 chore: script 모두 주석 처리
  scripts/application_stop.sh
  scripts/before_install.sh
  scripts/start.sh
Labels: chore

#39 chore: start , stop 스크립트 수정
  appspec.yml
  scripts/before_install.sh
  scripts/stop.sh
Labels: chore

#41 chore: / -> hello mozi로 응답
  src/loaders/express.ts
Labels: feature

#44 feat: PATCH todos/:id 엔드 포인트 변경
  src/controllers/todo.ts
  src/routes/todo.ts
  src/services/todo.ts
Labels: refactor

#46 feat: todo schema에 location field 추가
  src/models/todo.ts
  src/services/todo.ts
Labels: feature
