Repository team-yaza/mozi-server, pull requests merged in 2022-10, with the labels that each got.

#126 feat: Todo ownerId 필드 이름을 userId로 변경
  src/controllers/todo.ts
  src/models/index.ts
  src/models/todo.ts
  src/models/user.ts
  src/services/todo.ts
  src/types/todo.ts
  src/types/user.ts
Labels: refactor

#127 fix: deleteAll force option
  src/services/todo.ts
Labels: refactor

#128 feat: Api docs update
  src/controllers/location.ts
  swagger.yaml
Labels: documentation

#129 feat: Basic Todo CRUD test
  .github/workflows/ci.yml
  jest.config.js
  package.json
  src/index.ts
  src/services/todo.ts
  tests/index.ts
  tests/todo.test.ts
  tests/todo.ts
  yarn.lock
Labels: feature

#130 feat: Todo에 dueDate, alarmDate 추가
  src/models/index.ts
  src/models/todo.ts
  src/types/todo.ts
  swagger.yaml
Labels: feature

#131 feat: force Delete Todo
  src/controllers/todo.ts
  src/routes/todo.ts
  src/services/todo.ts
Labels: feature

#132 feat: POST createTodo parameter validation
  package.json
  src/controllers/todo.ts
  src/loaders/routes.ts
  src/middlewares/todo.ts
  src/routes/todo.ts
  src/services/todo.ts
  src/utils/error.ts
  swagger.yaml
  tests/todo.test.ts
  yarn.lock
Labels: feature

#133 feat: Sentry Error monitoring
  package.json
  src/index.ts
  src/loaders/routes.ts
  yarn.lock
Labels: feature

#134 feat: Prometheus client middleware
  package.json
  src/loaders/index.ts
  src/loaders/prom.ts
  tests/todo.test.ts
  yarn.lock
Labels: feature

#135 chore: remove unused vatiables
  src/loaders/routes.ts
Labels: chore

#136 fix: Exception handling
  .eslintrc.json
  src/index.ts
  src/loaders/routes.ts
  src/middlewares/auth.ts
  tests/todo.test.ts
Labels: feature

#138 feat: sequelize sync option
  src/index.ts
  src/loaders/sequelize.ts
  src/models/index.ts
Labels: feature

#139 refactor: sequelize sync에 대한 에러 처리
  src/loaders/sequelize.ts
Labels: refactor

#140 feat: sync controller, router
  src/controllers/todo.ts
  src/routes/todo.ts
Labels: feature

#144 feat: Map에서 주변이 아닌 장소도 검색할 수 있는 기능
  src/controllers/location.ts
  src/middlewares/location.ts
  src/routes/location.ts
  src/services/location.ts
  tests/location.test.ts
Labels: feature

#145 refactor: 3 Tier Architecture로 업그레이드를 위한 리팩토링
  .github/workflows/cd.yml
  docker-compose.yml
  src/loaders/sequelize.ts
Labels: refactor
