Repository team-yaza/mozi-server, pull requests merged in 2022-08, with the labels that each got.

#48 refactor: model들 timestamp 추가
  src/models/area.ts
  src/models/header.ts
  src/models/project.ts
  src/models/todo.ts
Labels: refactor

#50 feat: mongoose connection err 추가
  src/loaders/mongo.ts
Labels: chore

#55 fix: todo return type
  src/models/todo.ts
Labels: feature

#57 refactor: location update를 위한 GeoJson 모듈 생성
  src/services/todo.ts
  src/utils/serialize.ts
Labels: refactor

#56 feat: webpush 기본 기능 구현
  .eslintrc.json
  package.json
  public/client.js
  public/index.html
  public/worker.js
  src/index.ts
  src/loaders/express.ts
  src/routes/index.ts
  src/routes/webpush.ts
  yarn.lock
Labels: feature

#60 Swagger 적용
  package.json
  src/loaders/express.ts
  swagger.yaml
  yarn.lock
Labels: feature

#63 refactor: mozi-client에 맞게 web push api 변경
  .eslintrc.json
  public/client.js
  public/index.html
  public/worker.js
  src/loaders/express.ts
  src/routes/webpush.ts
Labels: refactor

#64 chore: cors option credentials off
  src/loaders/express.ts
Labels: chore

#65 feat: helmet middleware
  package.json
  src/loaders/express.ts
  yarn.lock
Labels: feature

#66 feat: todo notification
  src/controllers/webpush.ts
  src/routes/webpush.ts
  src/services/webpush.ts
Labels: feature

#67 fix: findAllTodo (if empty return null)
  src/controllers/todo.ts
  src/services/todo.ts
Labels: refactor

#68 chore: swagger code 정리 및 production 환경 지원
  package.json
  src/loaders/express.ts
  src/services/todo.ts
  yarn.lock
Labels: documentation

#72 fix: delete todo handler
  src/controllers/todo.ts
Labels: refactor

#73 fix: update todo 업데이트 된 값 반환
  src/services/todo.ts
Labels: bug

#74 feat: 로컬 로그인 기능
  package.json
  src/controllers/area.ts
  src/controllers/auth.ts
  src/controllers/header.ts
  src/controllers/project.ts
  src/loaders/express.ts
  src/loaders/index.ts
  src/loaders/passport.ts
  src/loaders/routes.ts
  src/middlewares/login.ts
  src/models/area.ts
  src/models/header.ts
  src/models/project.ts
  src/models/todo.ts
  src/models/user.ts
  src/routes/area.ts
  src/routes/auth.ts
  src/routes/header.ts
  src/routes/index.ts
  src/routes/project.ts
  src/services/area.ts
  src/services/auth.ts
  src/services/header.ts
  src/services/project.ts
  src/utils/kakaoStrategy.ts
  yarn.lock
Labels: documentation, feature

#77 chore: mongodb config (url)
  src/config/index.ts
  src/loaders/mongo.ts
Labels: chore

#80 chore: Todo 인터페이스 타입 에러 수정
  .github/workflows/ci.yml
  src/models/todo.ts
Labels: chore

#79 feat: 네이버 지도 api를 이용해서 좌표를 주소명으로 변환하기
  package.json
  src/utils/reverseGeocoding.ts
  src/utils/serialize.ts
  yarn.lock
Labels: feature

#82 refactor: 사용하지 않는 변수, 선언 제거
  .eslintrc.json
  src/controllers/auth.ts
  src/loaders/express.ts
  src/utils/reverseGeocoding.ts
Labels: chore

#83 chore: ESLint가 src 디렉토리만 검사하도록 설정
  package.json
Labels: chore

#84 feat: todo done column -> default false로 지정
  src/models/todo.ts
Labels: feature

#86 feat: pino logger
  README.md
  package.json
  src/index.ts
  src/loaders/mongo.ts
  src/utils/logger.ts
  yarn.lock
Labels: feature
